#!/usr/bin/env -S deno run -A
import { job, workflow } from "jsr:@david/gagen@^0.5.0";

const buildJob = job("build", {
  name: "check updates",
  if: "github.repository == 'dprint/dprint-plugin-biome'",
  runsOn: "ubuntu-latest",
  timeoutMinutes: 45,
  steps: [
    {
      name: "Clone repository",
      uses: "actions/checkout@v6",
      with: { token: "${{ secrets.GH_DPRINTBOT_PAT }}" },
    },
    { uses: "denoland/setup-deno@v2" },
    { uses: "dsherret/rust-toolchain-file@v1" },
    {
      name: "Run script",
      run: [
        `git config user.email "dprintbot@users.noreply.github.com"`,
        `git config user.name "dprintbot"`,
        "deno run -A ./scripts/update.ts",
      ],
    },
  ],
});

// This is necessary to prevent GH automatically disabling this workflow after 60 days.
const keepaliveJob = job("workflow-keepalive", {
  if: "github.event_name == 'schedule'",
  runsOn: "ubuntu-latest",
  permissions: { actions: "write" },
  steps: [
    { uses: "liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c" },
  ],
});

workflow({
  name: "check_updates",
  on: {
    workflow_dispatch: {},
    schedule: [{ cron: "0 7 * * *" }],
  },
  jobs: [buildJob, keepaliveJob],
}).writeOrLint({
  filePath: new URL("./check_updates.generated.yml", import.meta.url),
  header: "# GENERATED BY ./check_updates.ts -- DO NOT DIRECTLY EDIT",
  pinDeps: true,
});
