#!/usr/bin/env -S deno run -A
import { job, workflow } from "jsr:@david/gagen@^0.5.0";

const npmJob = job("build", {
  name: "publish-npm",
  runsOn: "ubuntu-latest",
  steps: [
    { uses: "actions/checkout@v6" },
    { uses: "dsherret/rust-toolchain-file@v1" },
    { name: "Install wasm32 target", run: "rustup target add wasm32-unknown-unknown" },
    {
      name: "Build release",
      run: "cargo build --target wasm32-unknown-unknown --features wasm --release",
    },
    {
      uses: "actions/setup-node@v6",
      with: {
        "node-version": "24.x",
        "registry-url": "https://registry.npmjs.org",
      },
    },
    {
      name: "Setup and test npm deployment",
      run: [
        "cd deployment/npm",
        "npm install",
        "node setup.js sync-version",
        "npm run test",
      ],
    },
    {
      name: "npm publish",
      run: [
        "cd deployment/npm",
        "npm publish --access public",
      ],
    },
  ],
});

workflow({
  name: "publish npm",
  on: {
    workflow_dispatch: {},
    push: { tags: ["*"] },
  },
  permissions: { "id-token": "write", contents: "read" },
  jobs: [npmJob],
}).writeOrLint({
  filePath: new URL("./publish_npm.generated.yml", import.meta.url),
  header: "# GENERATED BY ./publish_npm.ts -- DO NOT DIRECTLY EDIT",
  pinDeps: true,
});
